### ISSUE TITLE
ToT Error

### ISSUE THREAD

**Issue by Jikiro** [nmsmith22389/CandyUI#11]
I receive this error when i target any player who has a target already selected, quickest way i found to reproduce this is by targeting myself.

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:708: attempt to index a nil value
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:708: in function 'UpdateToT'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:178: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:171>

**Comment by nmsmith22389** [comment]
Should be fixed. I'm checking now.

Update: Fixed!
