### ISSUE TITLE
Missing Colors?

### ISSUE THREAD

**Issue by Jikiro** [nmsmith22389/CandyUI#12]
not sure if i am the only one having this issue but nameplates are just grey out, and ToT health area is just empty.

**Comment by nmsmith22389** [comment]
In the email it stated that nameplates aren't finished. They are being worked on now. As for the ToT frame that is definitely a bug. Thanks!

**Comment by nmsmith22389** [comment]
Can you try and get a screenshot of that tot bar next time it happens?

**Comment by Jikiro** [comment]
Ok well, i just checked out the update and it's fixed so it may have had something to do with the other ToT errors. if it was still there ten i would have made a screeny for ya but now it's working.

**Comment by Jikiro** [comment]
Ok it's back so i'll upload... and here ya go http://i.imgur.com/LNdtO8K.png
 it was working and i'm not sure when it went back to  this state, i have just been questing and that's about all. Nor have i received any scripting errors.

Reloadui does fix it however.

**Comment by nmsmith22389** [comment]
I'll look into it. Thanks! If I'm seeing the picture right it looks like its not showing that you have a shield in the ToT frame either so that could be the problem

**Comment by nmsmith22389** [comment]
I believe this should be fixed with the upcoming update.
