### ISSUE TITLE
Candy UI Options menu

### ISSUE THREAD

**Issue by cmgangrel** [nmsmith22389/CandyUI#15]
Although the options are indeed saving, the _displaying_ of this is not working correctly.

When I reloadui or relog into the game, all of the options for Nameplates (and the sub categories) are shown as unchecked even though their options are indeed checked (and saved as such).

**Comment by nmsmith22389** [comment]
Quote from the CandyUI Beta email:

> **CandyUI_Nameplates** - This addon is still very much not coded and will give you errors. Although this addon is not far enough along to be tested you are able to download it and may do so at your own discretion. Sending feedback, in the form of comments and suggestions, about this addon is OK but please do not post issues about this.

This addon is **largely** uncoded so much of it won't work. Work on it will be started very shortly and many of these things will be fixed / finished. Please keep posting feedback and issues though, just wait till the nameplates get a little further for posting about that addon Thanks!.
