### ISSUE TITLE
LUA Error Unit Frames

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#16]
Just received this error on the unit frames.  I was in Crimson Badlands and targeted the spiders that a dominion was killing.  I am exile.  The unit frames disappeared after the error and problem was resolved with a /reloadui

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:813: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:813: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:235: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

**Comment by nmsmith22389** [comment]
Im having trouble figuring this problem out. Are you still getting it?

**Comment by koquinn75** [comment]
No I have not received this error again.  It was just that one time.

**Comment by nmsmith22389** [comment]
Hmmm. Well if it comes up again let me know and open another issue. Thanks!
