### ISSUE TITLE
LUA Error on load in Nameplates

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#17]
Getting the following error occasionally when I first load my game.

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

**Comment by nmsmith22389** [comment]
Should be fixed but let me know if its not thanks!
