### ISSUE TITLE
Namplates Cannot turn off Player name / guild

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#18]
If I uncheck show on player and / or  uncheck all the options under player my guild still shows.  Occassionally when I zone into CB or Northern wastes both name and guild will show.  This is just player only.   If I go back into candyui options both buttons are checked under guild and cannot get it to save.

**Comment by nmsmith22389** [comment]
im working on fixing this right now. Thanks!

**Comment by nmsmith22389** [comment]
Try it now and see if its fixed...It should be.

**Comment by koquinn75** [comment]
Did the new code get uploaded for this?  I did not see a date change.  If it did the problem is still there as I just downloaded all the code for all modules and replaced what I had.

**Comment by nmsmith22389** [comment]
Try updating now. If it doesn't work still then I must have forgotten something. Either way let me know

**Comment by koquinn75** [comment]
It worked till I zoned into Northern Wastes.  Then both my name and guild showed back up.  I did a reloadui and they went away.  Same when I zoned back to Thayd from Northern wastes

**Comment by koquinn75** [comment]
It did the same thing going into Crimson Badlands.  BUT it did not do it in Northern Wastes when I zoned through the teleporter to the Robot section in Northern Wastes

**Comment by nmsmith22389** [comment]
Thanks! I'll check it out right now.

**Comment by koquinn75** [comment]
This has been fixed by the way
