### ISSUE TITLE
Nameplates

### ISSUE THREAD

**Issue by cmgangrel** [nmsmith22389/CandyUI#19]
When I login I have to reload the UI to get them to show, even though I am in an area that should show them.

**Comment by nmsmith22389** [comment]
Weird... I'll see if I can recreate it.

**Comment by nmsmith22389** [comment]
I think I see whats going on now. When this happens next, hit escape >> addons >> (nameplates addon) >> Show Errors and see if there are any errors. If the error text says "Options not loaded" then I know whats going on and am fixing it. This might sound a little complicated so if you need clarification let me know. Thanks!

**Comment by cmgangrel** [comment]
CandyUI Nameplates error:

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: attempt to index local 'unitPlayer' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:649: in function 'DrawName'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:517: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:426>

**Comment by nmsmith22389** [comment]
It should be fixed in the next update. If it still happens then reopen the issue or make a new one. Thanks!
