### ISSUE TITLE
Resource Bar Options and Text

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#21]
The text on the resource bar (Warrior) does not change and shows 0/0.   The bar does show resource being gained and loss and does change red and countdown on overdrive though.

Width setting does not change anything and position does not save on restart or reloadui.

**Comment by nmsmith22389** [comment]
At the time the text and width hadn't been coded. I have the width working now and text will also be done soon. Thanks!

**Comment by Mae-Is-Mean** [comment]
Location of resource bar still isn't saving for the characters that it loads on (mentioned characters it's not loading on in another post)

**Comment by nmsmith22389** [comment]
I would try it after the next update. It should be fixed but if you are still having problems let me know. Thanks!

**Comment by Mae-Is-Mean** [comment]
It is sort of saving... it seems to save the vertical, but not horizontal location. Or it's trying to center it on the screen, maybe.

**Comment by nmsmith22389** [comment]
Strange.... I'll check it out.

**Comment by nmsmith22389** [comment]
Yes it does not save horizontal. I'm going to close this issue and open a new one for the position. Thanks!
