### ISSUE TITLE
CandyUI_Unitframes:

### ISSUE THREAD

**Issue by cmgangrel** [nmsmith22389/CandyUI#26]
This error came when I tried to get on a hoverbike to complete part of theadventure. This was inside the Crimelords of Whitevale.

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:841: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:815: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:231: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

**Comment by cmgangrel** [comment]
Had this in a raid

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:825: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

**Comment by nmsmith22389** [comment]
Details on this error are covered in this issue: #31 . Thanks!
