### ISSUE TITLE
Unitframes

### ISSUE THREAD

**Issue by cmgangrel** [nmsmith22389/CandyUI#28]
This happened when I was in Genetic Archives, and a mob died. I believe that htis i because it couldn't track the rest of the mobs that it was linked to when it spawned more adds

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:813: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:813: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:235: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:222>

**Comment by nmsmith22389** [comment]
You might be using an older version which makes sense since your bug report isn't lining up with the code. Either way someone else posted the error also with the newer code here #31.
