### ISSUE TITLE
CandyUI_Resources

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#29]
Addon isn't loading, error I'm getting:

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:159: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:159: in function 'OnCreateEsper'
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:140: in function 'OnCharacterCreated'
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:119: in function 'CheckIfLoaded'
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:112: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:87>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:183: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:176>

**Comment by Mae-Is-Mean** [comment]
Same on my medic. The rest are OK with resource bar showing.

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:414: attempt to index field 'wndMain' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:414: in function 'OnCreateMedic'
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:144: in function 'OnCharacterCreated'
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:119: in function 'CheckIfLoaded'
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:112: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:87>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: attempt to index field '?' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:458: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:434>

**Comment by nmsmith22389** [comment]
Ive got it fixed. I'll update it when I get a chance. Thanks!
