### ISSUE TITLE
CandyUI_Nameplates

### ISSUE THREAD

**Issue by cmgangrel** [nmsmith22389/CandyUI#30]
This happened when I zoned into some ones housing plot

...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:1128: bad argument #1 to 'CanBeHarvestedBy' (invalid unit)
stack trace:
    [C]: in function 'CanBeHarvestedBy'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:1128: in function 'CheckVisibilityOptions'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:448: in function 'UpdateNameplateVisibility'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:417: in function 'UpdateAllNameplateVisibility'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:370: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:369>

**Comment by nmsmith22389** [comment]
Think I have it fixed for the next update. When the update is up, let me know if it works.
