### ISSUE TITLE
UnitFrames error when using "vehicle"

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#31]
Doing the quest "Bot's Eye View" in Whitevale, got this error when transforming to the bot:

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:853: bad argument #1 to 'floor' (number expected, got nil)
stack trace:
    [C]: in function 'floor'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:853: in function 'SetBarValue'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:827: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:243: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

**Comment by nmsmith22389** [comment]
I think I have it fixed but it's kind of a difficult thing to test. I'll update it when I get a chance.

**Comment by nmsmith22389** [comment]
Open another issue if the problem keeps popping up. Thanks!
