### ISSUE TITLE
CandyUI_Nameplates

### ISSUE THREAD

**Issue by cmgangrel** [nmsmith22389/CandyUI#35]
Lua event handler has exceeded 3789 ms.
stack trace:
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:439: in function 'UpdateNameplateVisibility'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:418: in function 'UpdateAllNameplateVisibility'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:371: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:370>

**Comment by nmsmith22389** [comment]
I got this once too. I'm trying to figure out why it's doing it but can't seem to figure it out.

**Comment by nmsmith22389** [comment]
The error doesn't seem to be happening anymore, possibly due to the new module loading code, but if you start getting this again please reopen the issue or create a new one. Thanks!
