### ISSUE TITLE
StarPanel still erroring

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#38]
Still getting this error on my Engy (haven't played other classes to see if they're getting it)

...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1720: attempt to index global 'g_wndActionBarResources' (a nil value)
stack trace:
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1720: in function <...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1709>

**Comment by ZataH** [comment]
...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:916: attempt to index field 'Currency' (a nil value)
stack trace:
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:916: in function 'InitializeDataTexts'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:240: in function <...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:193>

**Comment by Mae-Is-Mean** [comment]
FYI, did not get this error at all last night on my Medic, and I played her a few hours.

**Comment by nmsmith22389** [comment]
This should be fixed.
