### ISSUE TITLE
Unit Frames - Font

### ISSUE THREAD

**Issue by ZataH** [nmsmith22389/CandyUI#39]
"Medium" and "Large" almost seems to be the same size? 
Could it be possible to choose from a list of fonts?

**Comment by nmsmith22389** [comment]
Yeah I suppose I could do that but there really is only a few fonts. For the most part they are just different sizes.

**Comment by nmsmith22389** [comment]
Hey so it took so long but I've added a "Huge" font option. It's untested so there may be some clipping but it's definitely bigger.
