### ISSUE TITLE
CandyBars error every time I log in

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#41]
I get this every single time on first log in of a character. A /reloadui almost always fixes it. I am not sure if it's related to the Nameplates, but when it happens, my nameplates addon loads, no error, but I don't actually see nameplates until I target something, then ONLY that nameplate shows up. Just wanted to mention that as they may be related (since both happen at the same time, every time).

...aming\NCSOFT\WildStar\Addons\CandyBars\CandyBars.lua:532: attempt to index field 'tActionBarsHorz' (a nil value)
stack trace:
    ...aming\NCSOFT\WildStar\Addons\CandyBars\CandyBars.lua:532: in function <...aming\NCSOFT\WildStar\Addons\CandyBars\CandyBars.lua:531>

**Comment by nmsmith22389** [comment]
very strange... I'll check it out

**Comment by nmsmith22389** [comment]
I think I've got it figured out

**Comment by nmsmith22389** [comment]
Have you had anymore problems with it?

**Comment by Mae-Is-Mean** [comment]
I'm not getting the error anymore, but I do notice that the menu bar (the one at the top left) doesn't fully load on startup. I almost always need to /reloadui to get it to show.

**Comment by Mae-Is-Mean** [comment]
After updating last night, the menu bar seemed to be loading correctly on start up, most of the time. There was one time that all but the mail button loaded, other than that, they loaded correctly through many log ins. Never got an addon error tho.

**Comment by nmsmith22389** [comment]
I'm going to close this because I think it's fixed, but if you see it pop up again just post a new issue. Thanks!
