### ISSUE TITLE
Medic's resource bar

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#42]
The animation of the individual bubbles of the resource bar doesn't work. As it's filling, instead, the entire bar just looks full. What ends up happening is that if you don't fill an entire bubble (getting interrupted/dodging mid-cast) then the bar appears to be totally full, and then it's impossible to tell how many bubbles you're working with. Hope this makes sense ;)

**Comment by Mae-Is-Mean** [comment]
Not sure if this is part of the resource bar, but my spellslinger doesn't show a charge bar for charged spells (ie Charged Shot), nor does it show a countdown for limited-cast abilities (ie. Rapid Fire).

**Comment by nmsmith22389** [comment]
Isn't that part of the cast bar (of which I haven't made a replacement for
yet)? I'd recommend using SCast (sp?). I'm also curious as to why the stock
cast bar isn't showing it for you.

**Comment by Mae-Is-Mean** [comment]
No idea, but added SCast and it works, thank you!

**Comment by nmsmith22389** [comment]
Medic problem should be fixed in the most recent update!
