### ISSUE TITLE
CandyUI_Minimap

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#47]
New Minimap is spitting out this error if you hit the call button with no calls:

...\WildStar\Addons\CandyUI_Minimap\CandyUI_Minimap.lua:1465: attempt to index a nil value
stack trace:
    ...\WildStar\Addons\CandyUI_Minimap\CandyUI_Minimap.lua:1465: in function <...\WildStar\Addons\CandyUI_Minimap\CandyUI_Minimap.lua:1452>

Haven't tried it with a missed call.

**Comment by nmsmith22389** [comment]
The call button is in great disarray. For now I have it serving as a misc. button that is programmable. I'm actually not sure if the call button is even needed. Can't you just hit "C" or am I missing something?
