### ISSUE TITLE
Starpanel Error 

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#48]
I get this error anytime I run starpanel.  The panel is at the top but blank.

...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:921: attempt to index field 'Currency' (a nil value)
stack trace:
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:921: in function 'InitializeDataTexts'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:240: in function <...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:193>

**Comment by Mae-Is-Mean** [comment]
I would get this on characters that hadn't set up their starpanels yet. Once I set them up (by copying an existing profile) it stopped happening.

**Comment by koquinn75** [comment]
I will look into that tonight.  I haven't seen may options to set it up but haven't looked either.  Will report back.  Thanks Mae

**Comment by nmsmith22389** [comment]
Either way it needs to be fixed. I'll get working on it right away. Thanks!

**Comment by nmsmith22389** [comment]
I've got this fixed in the upcoming update. Thanks!

**Comment by koquinn75** [comment]
Seems to be working correctly now with the latest update
