### ISSUE TITLE
UnitFrames - Beginning of GA

### ISSUE THREAD

**Issue by ZataH** [nmsmith22389/CandyUI#49]
...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: attempt to index field '?' (a nil value)
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:832: in function 'UpdateClusters'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:247: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:234>

**Comment by cmgangrel** [comment]
Is this when you kill the mobs that split up until multiples on death? If so, this is what sparked off one of my errors that I posted about.

**Comment by ZataH** [comment]
Ehm this is some time ago now, so i cant remember that.

**Comment by nmsmith22389** [comment]
Oh dang! I'm sorry! I'll see what I can do to get this fixed. Thanks!

**Comment by nmsmith22389** [comment]
Should be fixed in the upcoming version but please don't hesitate to reopen the issue if the problem persists. Thanks!
