### ISSUE TITLE
CandyUI_NamePlates

### ISSUE THREAD

**Issue by LynxAU** [nmsmith22389/CandyUI#5]
for some reason it isnt showing up all the nameplates in my raid group

http://puu.sh/blU8r/c26562a31f.jpg

**Comment by nmsmith22389** [comment]
Yeah its just because it still needs a lot of work.

**Comment by nmsmith22389** [comment]
by the way i got skype its neil.smith.89

**Comment by nmsmith22389** [comment]
Yeah nameplates still need a lot of work but I want to try and get the
unitframes finished first. Im gonna send them out for testing in just a
little bit
