### ISSUE TITLE
Very weird StarPanel bug

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#50]
After the megaservers hit, I left my guild and remained without a guild for a while. My guild count on StarPanel changed to show my circle instead. Now that I'm in a new guild, it continues to show my circle count. I have no idea how to force it back to guild. Not getting any errors, but it just doesn't want to work =(

**Comment by nmsmith22389** [comment]
Yeah I just tried it out and you're right. I must have just coded it wrong. I'll get it fixed. Thanks!

**Comment by Mae-Is-Mean** [comment]
Just wanted to add that this is still happening. I left the circle I was in and now I'm in no circles and only the one guild. It shows the guild name, but it's not displaying a number of who's online =/

**Comment by eviilwave** [comment]
Thanks, Mae! This should be a fairly easy fix. We will do our best to get it resolved tonight ♥

**Comment by nmsmith22389** [comment]
This should be fixed in the upcoming update. Let me know if the problem comes back. Thanks!
