### ISSUE TITLE
CandyUI Options causes housing bar to not show

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#54]
Since the last update when I got to my housing plot the bar is missing to manage housing (repair, etc).  If I turn off all CandyUI addons it shows but as soon as I add CandyUI_Options back it dissapears.

**Comment by nmsmith22389** [comment]
Try enabling "Enable Shortcut Bars" in the CandyBars options

**Comment by koquinn75** [comment]
That fixed it

**Comment by nmsmith22389** [comment]
I need to figure out a way to make this easier or automatic for new users. If you have any ideas I'm all ears!
