### ISSUE TITLE
Nameplates annoyance

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#55]
Not necessarily an issue, more of an annoyance. There are "extra" nameplates that show up often in the game, and as far as I can tell, no way to turn them off. I'll attach some screenshots to show what I mean. The easiest place to see this is the very first Drusera instance at level 35. There are "friendly" nameplates that cannot be turned off. They are not part of the "Show Simple" form the general tab of options, they're not linked to Show NPC in the Friendly tab. They're just kind of always there. I've used other nameplate addons that did not show them, and some that do, so I am sure there's a way to turn them off. It can get pretty overwhelming in some places, particularly if you like to keep NPC nameplates showing.
![maedelyn_mae 141107 113444](https://cloud.githubusercontent.com/assets/8868659/4959315/43539af2-66b7-11e4-9184-f97fe546463f.png)
![maedelyn_mae 141107 113501](https://cloud.githubusercontent.com/assets/8868659/4959317/438b830e-66b7-11e4-98d5-251672ffb78d.png)

**Comment by nmsmith22389** [comment]
Yeah sorry this is something I still need to get fixed. I've noticed it too. Thanks for posting this!

**Comment by nmsmith22389** [comment]
I think I have this fixed in the upcoming update. Although I haven't tested it. There are if statements all over the place its such a mess but i think it should work. It definitely needs some cleaning up.
