### ISSUE TITLE
Starpanel autohide on game start

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#56]
I have starpanel setup on the bottom with autohide background.  When I start the game it goes to autohide and not just autohide background.  I have to uncheck the 2 boxes (show bar and auto hide background) to get it back the way I set it.

**Comment by nmsmith22389** [comment]
I'll check it out. Thanks!

**Comment by nmsmith22389** [comment]
Sorry about that! For setting the bottom bar when the game loads I had the AutoFade command typed in for the Autohide BG option instead of AutoFadeBG. Everything should work as intended in the next update. Thanks!
