### ISSUE TITLE
Since update 11/13

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#57]
Others have commented on the same bug. Most the addons fail and this error spits out: 

...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:77: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...FT\WildStar\Addons\Interruptor\Libs/GeminiDB-1.0.lua:523: in function 'SetProfile'
    ...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:77: in function 'OnDocLoaded'
    ...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:65: in function <...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:62>

**Comment by nmsmith22389** [comment]
I just uploaded an update that should fix it. At least I hope so. See it's kind of crazy because each of the candyUI addons has a profile and they should all be on the same profile but it seems like the Datachron just doesn't want to cooperate. Let me know if you keep having problems. Thanks!

**Comment by Mae-Is-Mean** [comment]
Posted on forums with new bug errors. Most the addons still don't load.

**Comment by Mae-Is-Mean** [comment]
Newest update still getting errors. Here are all of them:

Datachron:
...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:212: attempt to index global 'g_DatachronButton' (a nil value)
stack trace:
    ...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:212: in function 'OnMinimizeDatachron'
    ...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:139: in function 'OnDocLoaded'
    ...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:65: in function <...dStar\Addons\CandyUI_Datachron\CandyUI_Datachron.lua:62>

Dash:
...NCSOFT\WildStar\Addons\CandyUI_Dash\CandyUI_Dash.lua:68: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...Star\Addons\CandyBars\Libs/GeminiDB/GeminiDB-1.0.lua:452: in function 'SetProfile'
    ...NCSOFT\WildStar\Addons\CandyUI_Dash\CandyUI_Dash.lua:68: in function <...NCSOFT\WildStar\Addons\CandyUI_Dash\CandyUI_Dash.lua:62>

InterfaceMenu:
...dons\CandyUI_InterfaceMenu\CandyUI_InterfaceMenu.lua:83: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...Star\Addons\CandyBars\Libs/GeminiDB/GeminiDB-1.0.lua:452: in function 'SetProfile'
    ...dons\CandyUI_InterfaceMenu\CandyUI_InterfaceMenu.lua:83: in function <...dons\CandyUI_InterfaceMenu\CandyUI_InterfaceMenu.lua:77>

MiniMap:
...\WildStar\Addons\CandyUI_Minimap\CandyUI_Minimap.lua:309: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...Star\Addons\CandyBars\Libs/GeminiDB/GeminiDB-1.0.lua:452: in function 'SetProfile'
    ...\WildStar\Addons\CandyUI_Minimap\CandyUI_Minimap.lua:309: in function <...\WildStar\Addons\CandyUI_Minimap\CandyUI_Minimap.lua:305>

Nameplates:
...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:213: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...Star\Addons\CandyBars\Libs/GeminiDB/GeminiDB-1.0.lua:452: in function 'SetProfile'
    ...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:213: in function <...tar\Addons\CandyUI_Nameplates\CandyUI_Nameplates.lua:209>

Options:
...\WildStar\Addons\CandyUI_Options\CandyUI_Options.lua:175: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...Star\Addons\CandyBars\Libs/GeminiDB/GeminiDB-1.0.lua:452: in function 'SetProfile'
    ...\WildStar\Addons\CandyUI_Options\CandyUI_Options.lua:175: in function <...\WildStar\Addons\CandyUI_Options\CandyUI_Options.lua:122>

Resources:
...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:93: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...Star\Addons\CandyBars\Libs/GeminiDB/GeminiDB-1.0.lua:452: in function 'SetProfile'
    ...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:93: in function <...dStar\Addons\CandyUI_Resources\CandyUI_Resources.lua:87>

Unit Frames:
...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:78: Usage: GeminiDBObject:SetProfile(name): 'name' - string expected.
stack trace:
    [C]: in function 'error'
    ...Star\Addons\CandyBars\Libs/GeminiDB/GeminiDB-1.0.lua:452: in function 'SetProfile'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:78: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:75>

**Comment by Mae-Is-Mean** [comment]
Ok, everything is working now, BUT, you need to update StarPanel on Curse!

**Comment by nmsmith22389** [comment]
Thanks!
