### ISSUE TITLE
Path Frame

### ISSUE THREAD

**Issue by mistik911** [nmsmith22389/CandyUI#58]
Hey, I have two issues I ran into with CandyUI. I only have CandyUI installed at the moment and i did a clean reset of my interface. The first is that under addons is says that the Path Frame is suspended and is red. I took a picture here:

![Addons](https://cloud.githubusercontent.com/assets/9784191/5061812/90165a18-6d75-11e4-918d-9c497c30fd8f.png)

Secondly, I play a scientist and the path frame in the bottom right does not have the bot controls and summon part of the frame, but it looks like the old frame is trying to overlap your texture. I took a picture of it also:

![pathframe](https://cloud.githubusercontent.com/assets/9784191/5061819/2862c892-6d76-11e4-9d15-8b787ce8c69c.png)

I dont know if this helps you at all but i thought I would bring them to your attention. THANK YOU!, For making this awesome addon.

**Comment by nmsmith22389** [comment]
Hello and thanks for posting! The PathFrame is red because its supporting addons have been disabled. It won't hurt anything though because PathFrame should be disabled as well. As for the scientist panel issue, I'm aware of the problem and am working on getting it fixed. Hope that helps. Thanks!

**Comment by nmsmith22389** [comment]
I've got the scientist display fixed for the upcoming update. Thanks!
