### ISSUE TITLE
Problem at loading Starpanel

### ISSUE THREAD

**Issue by bcarmard** [nmsmith22389/CandyUI#60]
Hello, and thank you for your work !

For your information, when loading my UI, I get the following error message : 

...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:969: attempt to index a nil value
stack trace:
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:969: in function 'OnTooltip'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1284: in function 'CreateDataTextsTop'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1653: in function 'RefreshTopDisplay'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1224: in function 'InitializeDataTexts'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:285: in function <...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:224>

And Either all information displayed on star panel are stacked or only one appears

**Comment by bcarmard** [comment]
Modifying alignment solves the problem until UI has to load again.

**Comment by nmsmith22389** [comment]
Hi! Ive got this fixed in the next update. Thanks!
