### ISSUE TITLE
Unit Frame Options (Absorbs)

### ISSUE THREAD

**Issue by ARX-7** [nmsmith22389/CandyUI#62]
Is there any way to make the Absorbs Not fully cover the health?

A solution i liked was in VikingHug, where the absorb wasn't as high as the rest of the health bar so you  could see through to it.

**Comment by eviilwave** [comment]
Would adding an opacity slider to the absorb bar help? Or am I misunderstanding your question?

Thank you for bringing this up! 
♥

**Comment by nmsmith22389** [comment]
I added an opacity slider for the absorb bar in the next update for you.Thanks!

**Comment by ARX-7** [comment]
On thinking on it, this should adress my issue, thanks.
