### ISSUE TITLE
Are we getting an update soon?

### ISSUE THREAD

**Issue by Mae-Is-Mean** [nmsmith22389/CandyUI#64]
I know it's the holidays, and I don't expect you to work through them, but just wondering if there's an update expected soon (like after the New Year)? I am 99.9% happy with the UI, with my only constant bugs being the scientist datachron being goofy looking, and the menu bar not loading completely every time (which I know is a tough one to figure out).

**Comment by nmsmith22389** [comment]
Hey! Sorry for the hiatus but yes I'm actually working on it right now. Thanks!

**Comment by coding-red-panda** [comment]
new versions are being published, just waiting on curse to stop rejecting our changes
