### ISSUE TITLE
Starpanel loading and realtime update issue

### ISSUE THREAD

**Issue by bcarmard** [nmsmith22389/CandyUI#65]
Hello, 

I'm still having a issue each time my ui has to load, I get the following error : 

...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1292: bad argument #1 to 'AppendText' (string expected, got function)
stack trace:
    [C]: in function 'AppendText'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1292: in function 'CreateDataTextsTop'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1672: in function 'RefreshTopDisplay'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:1243: in function 'InitializeDataTexts'
    ...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:285: in function <...aming\NCSOFT\WildStar\Addons\StarPanel\StarPanel.lua:224>

And star panel datas seems to be frozen to it's initial state after this error happens

**Comment by coding-red-panda** [comment]
This will be fixed in #70
