### ISSUE TITLE
CandUI_Options replaces ActionBarFrame

### ISSUE THREAD

**Issue by ARX-7** [nmsmith22389/CandyUI#67]
Due to the above add-on doesn't allow the default action bar frames to load, i do not have Candy bars installed and given it is a separate add-on the options shouldn't be doing this

**Comment by coding-red-panda** [comment]
Valid point.
Making the change in the code that CandyBars should replace that Addon and not CandyUI_Options.
Should be resolved on next Beta release.

**Comment by coding-red-panda** [comment]
This is resolved in 0.5
