### ISSUE TITLE
Engie Tooltip Error

### ISSUE THREAD

**Issue by ChargeIn** [nmsmith22389/CandyUI#76]
If you hover over the Go TO button of the engineer bots you get an error saying:

"GetFlavor is deprecated. GetTooltips should be used instead."

![candyui_bug_bots](https://cloud.githubusercontent.com/assets/26235155/23753171/afe67ad8-04d8-11e7-8801-0c46d9e3d4ba.png)

**Comment by ChargeIn** [comment]
So did some testing GetTooltips gives back: 
![gettooltip](https://cloud.githubusercontent.com/assets/26235155/23754287/bd3dee06-04dc-11e7-8234-54eee2556993.png)

**Comment by ChargeIn** [comment]
tried it with "strCasterTootltip" works fine, but not sure if its the correct one

**Comment by coding-red-panda** [comment]
strCasterTooltip should be fine as you are the caster
