### ISSUE TITLE
Unitframes not working

### ISSUE THREAD

**Issue by Rotaq** [nmsmith22389/CandyUI#77]
So far everything seems to work without a problem except for the Unitframes.
I get this error everytime i try to enable it.
...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:650: attempt to call global 'SendVarToRover' (a nil value)
stack trace:
	...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:650: in function 'UpdateIntArmor'
	...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:634: in function 'UpdateUnitFrame'
	...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:228: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:220>

**Comment by coding-red-panda** [comment]
Ack seems we left that code in, will toss it out from the master code branch

**Comment by coding-red-panda** [comment]
If you comment out line 650 in CandyUI_UnitFrames/CandyUI_UnitFrames.lua i should work actually.

**Comment by Rotaq** [comment]
While you're here i just discovered another issue.
On the mount button it shows every mount available instead of the ones i own.

**Comment by Rotaq** [comment]
Not really sure how to do that

**Comment by coding-red-panda** [comment]
We're aware of the mount button issue, I'll open a seperate issue for that and close this down.
The mount issue is known; but I'll need a bit of debugging to get that on working

**Comment by Rotaq** [comment]
If you comment out line 650 in CandyUI_UnitFrames/CandyUI_UnitFrames.lua i should work actually.

How exactly do i do this?

**Comment by coding-red-panda** [comment]
Open the file in %AppData%\roaming\Ncsoft\Wildstar\addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua

Find every line that has SendVarToRover and make sure it has -- at the front of it.
`--` puts stuff as comment in Lua

**Comment by Rotaq** [comment]
That worked, thanks man!

Awesome UI so far i really like it.
