### ISSUE TITLE
White text behind nameplate bars

### ISSUE THREAD

**Issue by coding-red-panda** [nmsmith22389/CandyUI#79]
![source](https://cdn.discordapp.com/attachments/289680446231412736/289680505715163136/unknown.png)

Seems there's an issue with the text appearing behind the bars instead of in front of it.

**Comment by ChargeIn** [comment]
thx, because engis didn't have a focus bar , i couldn't notice

Fixded it and made a pull request

**Comment by coding-red-panda** [comment]
you'll need to rebase first, as the structure of the project had to change to support Curse's automated packaging system.

**Comment by ChargeIn** [comment]
how do i do that just creating a new fork  ? never worked with github before
