### ISSUE TITLE
Spellslinger ChargeBar

### ISSUE THREAD

**Issue by ChargeIn** [nmsmith22389/CandyUI#81]
There is no bar that shows how many charges of an Ability you have , e.g. Vitality Burst can be charged up 3 times . Sadly its unplayable for spellslinger if you can see this :/

![chargebar](https://cloud.githubusercontent.com/assets/26235155/23797530/98ea1d44-05a0-11e7-903a-2f77d33c8c2f.png)

**Comment by coding-red-panda** [comment]
Can this be closed @ChargeIn ?

**Comment by ChargeIn** [comment]
jep can be closed is fixed , not perfect but they work
