### ISSUE TITLE
Cannot move unit frames

### ISSUE THREAD

**Issue by ZataH** [nmsmith22389/CandyUI#82]
What am i doing wrong here? I cannot move the unit frames. Only managed to move the focus frame.

**Comment by hellhound-omega** [comment]
Same here. I can move everything else by CTRL+L Click, but not the unit frames.

**Comment by coding-red-panda** [comment]
we'll take a look at it!
Thanks for reporting this, could be we missed one of the window elements to support this

**Comment by coding-red-panda** [comment]
Okay,

I've found the problem for this:

* windows are marked as moveable
* but they ignore mouse events.

This means we need to build in a toggle feature to swap between "normal" and "edit" mode similar to what RaidCore does. Enabling the mode allows you to drag all units around. Disabling the mode then makes them ignore all mouse functionality again.

Shouldn't be too hard to do, but will require a bit of time.

**Comment by coding-red-panda** [comment]
will  be fixed in v0.6
