### ISSUE TITLE
ToT Settings

### ISSUE THREAD

**Issue by koquinn75** [nmsmith22389/CandyUI#9]
I get the following error when trying to change ToT health text to any of the options (show, hover, or hide)

...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:1233: attempt to index a nil value
stack trace:
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:1233: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:1230>
    [C]: in function 'Show'
    ...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:1227: in function <...tar\Addons\CandyUI_UnitFrames\CandyUI_UnitFrames.lua:1220>

It does change to the setting I set to but this error pops up.  Even after a reloadui and client restart.  Setting does stay after a reload or restart.

**Comment by Jikiro** [comment]
I have also reproduced this error

**Comment by nmsmith22389** [comment]
Error was do to capitalization. Fixed.
