### ISSUE TITLE
No minimap port

### ISSUE THREAD

**Issue by Orcsplitter** [nmsmith22389/CandyUI#92]
There currently does not appear to be a "Rapid Transport" on the minimap.  

No apparent way to move the bar (lower left of screen) that has mail, contracts, friends, social, account inventory, etc.  

When pressing the (-) sign on the minimap it produces an empty grey block at the bottom right of the screen.

**Comment by coding-red-panda** [comment]
* Rapid Transport will be added asap, need to copy that over from the original minimap addon.
* Those bars should be top and bottom, extending across the entire screen. Can you provide a screenshot if they are not ?
* YEs, Datachron is currently not working at all, which is gonne be a huge effort to get that one going.

**Comment by Orcsplitter** [comment]
![splak_oopsenboom 170321 180947](https://cloud.githubusercontent.com/assets/26517458/24174943/9cbaeb00-0e61-11e7-9607-70b9935224c2.png)

The bar I am talking about is the little bar in the upper left of the screen, not the starbar.

**Comment by coding-red-panda** [comment]
Aaah that's the main menu :D
Can look into making that one moveable as well.
Guess adding one more to the windowmanager won't make a difference

**Comment by Orcsplitter** [comment]
Thanks for all that you guys are doing.
