### ISSUE TITLE
AbsorbBars

### ISSUE THREAD

**Issue by ChargeIn** [nmsmith22389/CandyUI#96]
When absorb is applied to the unti you can not seee you current health, so it could be that you have 1 hp but your bar is full because of absob

Made a fix for it but the sprites need to be reajusted for the corners
![absorb](https://cloud.githubusercontent.com/assets/26235155/24194664/31405554-0ef7-11e7-9fed-e8d46a8ab831.png)

**Comment by ChargeIn** [comment]
https://github.com/ChargeIn/CandyUI haven't tested the fix much
, but if you want to take a look at it i uploaded it to the fork

**Comment by coding-red-panda** [comment]
best to open a pull-request when you can.
Way easier to see code changes that way.

**Comment by ChargeIn** [comment]
sadly not , github is still broken for me , it will just tell you everything changed :/ , 
well since its not much code , i will manually change everything in  github and make a request.
(maybe i can change my editor to make it work , which are you using ?)
